name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Hostinguer
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Instalar dependências do Vue.js
    - name: Install dependencies
      run: npm install

    # 3. Construir o projeto (build)
    - name: Build the project
      run: npm run build

    # 4. Configurar chave SSH
    - name: Setup SSH key
      run: |
        echo "Setting up SSH key..."
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 65002 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    # 5. Testar a configuração do SSH
    - name: Check SSH setup
      run: |
        echo "Checking SSH key and directory..."
        ls -la ~/.ssh/

    # 6. Deploy inicial para a pasta raiz
    - name: Deploy main files
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002
        source: ./dist/* # Apenas o conteúdo da pasta dist
        target: /home/u741651436/domains/regionalmotors.com.br/public_html/teste/

    # 7. Distribuir os arquivos para subpastas específicas
    - name: Deploy to subdirectories
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 65002 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          # Copiar arquivos da pasta raiz para revenda1
          rsync -av --remove-source-files /home/u741651436/domains/regionalmotors.com.br/public_html/teste/ /home/u741651436/domains/regionalmotors.com.br/public_html/teste/revenda1/
          # Copiar arquivos da pasta raiz para revenda2
          rsync -av --remove-source-files /home/u741651436/domains/regionalmotors.com.br/public_html/teste/ /home/u741651436/domains/regionalmotors.com.br/public_html/teste/revenda2/
          # Limpar diretórios vazios restantes após mover arquivos
          find /home/u741651436/domains/regionalmotors.com.br/public_html/teste/ -type d -empty -delete
        EOF
