name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Hostinguer
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Instalar dependências do Vue.js
    - name: Install dependencies
      run: npm install

    # 3. Construir o projeto (build)
    - name: Build the project
      run: npm run build

    # 4. Criando chave SSH
    - name: Setup SSH key
      run: |
        echo "Setting up SSH key..."
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 65002 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    # 5. Checando SSH
    - name: Check SSH setup
      run: |
        echo "Checking SSH key and directory..."
        ls -la ~/.ssh/

    # 6. Deploy dos arquivos principais para a raiz
    - name: Deploy main files
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002
        source: ./dist/ # Arquivos gerados no build
        target: |
          /home/u741651436/domains/regionalmotors.com.br/public_html/revenda1
          /home/u741651436/domains/regionalmotors.com.br/public_html/revenda2

