name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Hostinguer
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Instalar dependências do Vue.js
    - name: Install dependencies
      run: npm install

    # 3. Construir o projeto (build)
    - name: Build the project
      run: npm run build

    # 4. Deploy dos arquivos principais para a raiz
    - name: Deploy main files
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASS }}
        port: 65002
        source: dist/* # Arquivos gerados no build
        target: /home/u741651436/public_html

    # 5. Copiar arquivos para as subpastas
    - name: Deploy to subdirectories
      run: |
        ssh -o StrictHostKeyChecking=no your-ssh-user@your-server-ip << EOF
          cp -r /home/u741651436/public_html/* /home/u741651436/public_html/revenda1/
          cp -r /home/u741651436/public_html/* /home/u741651436/public_html/revenda2/
        EOF
