name: Continuous Deployment

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to Hostinguer
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar dependências do Vue.js
      - name: Install dependencies
        run: npm install

      # 3. Construir o projeto (build)
      - name: Build the project
        run: npm run build

      # 4. Criando chave SSH
      - name: Setup SSH key
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 65002 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 5. Checando SSH
      - name: Check SSH setup
        run: echo "Checking SSH key and directory..."

      # 6. Deploy na Dist
      - name: Deploy files to Regional Motors directory
        run: |
          shopt -s extglob  # Ativa o extglob no bash

          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Branch: main. Deploy para 'regionalmotors.com.br'"
            scp -P 65002 -r ./dist/!(index.html) ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u741651436/domains/regionalmotors.com.br/public_html/
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            echo "Branch: develop. Deploy para 'revendarm.com.br' e 'homologrm.com.br'"
            
            # Deploy para 'revendarm.com.br'
            echo "Deploy para 'revendarm.com.br'..."
            scp -P 65002 -r ./dist/!(index.html) ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u741651436/domains/revendarm.com.br/public_html/
            
            # Deploy para 'homologrm.com.br'
            echo "Deploy para 'homologrm.com.br'..."
            scp -P 65002 -r ./dist/!(index.html) ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u741651436/domains/homologrm.com.br/public_html/
          
          else
            echo "Nenhum deploy configurado para a branch: ${{ github.ref_name }}"
          fi


      # 7. Deploy dos arquivos para múltiplos diretórios
      - name: Deploy files to revendas directories
        run: |
          shopt -s extglob  # Ativa o extglob no bash
          # Consultar a API e salvar os sites em folders.txt
          curl -s -X GET "https://api.regionalmotors.com.br/api/anunciantes/buscar_site_anunciante" | jq -r '.[].site' > folders.txt
          FOLDERS=$(cat folders.txt)
          
          # Verificar qual branch está sendo usada
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Branch: main. Fazendo deploy para todos os sites retornados pela API."
          
            # Iterar sobre os sites retornados pela API
            for folder in $FOLDERS; do
              echo "Criando pasta $folder no servidor..."
              ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 65002 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /home/u741651436/domains/$folder/public_html/"
              ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 65002 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -ld /home/u741651436/domains/$folder/public_html/"

              echo "Fazendo deploy para $folder..."
              scp -P 65002 -r ./dist/!(index.html) ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u741651436/domains/$folder/public_html/
            done
          
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            echo "Branch: develop. Nenhuma ação será executada."
          
          else
            echo "Nenhum deploy configurado para a branch: ${{ github.ref_name }}."
          fi
